# Model arguments
model_name_or_path: Qwen2.5-VL-7B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: clevrer_counterfactual_train
jsonl_path: CLVERER/clevrer_counterfactual_train.json
preprocessing_num_workers: 1

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
push_to_hub: false
hub_model_id: null
hub_strategy: "end"
learning_rate: 1.0e-04
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: Qwen2.5-VL-7B-Instruct-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
report_to:
- wandb
save_strategy: "steps"
save_steps: 10
save_total_limit: 10
save_safetensors: true
seed: 42
warmup_ratio: 0.1
